<?php 
    class LoanRepository {
        private PDO $pdo;

        public function __construct(PDO $pdo) {
            $this->pdo = $pdo;
        }

        public function insertLoan(Loan $loan) : int {
            try {
                $sql = "INSERT INTO Loans (LoanDate, DueDate, MemberID)
                                    VALUES(:cloanDate, :cdueDate, :cmemberID)";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cloanDate', $loan->getLoanDate()->format('Y-m-d'));
                $stmt->bindValue(':cdueDate', $loan->getDueDate()->format('Y-m-d'));
                $stmt->bindValue(':cmemberID', $loan->getMemberID());

                $stmt->execute();
                return (int) $this->pdo->lastInsertId(); // get the loan ID generated by maria db for loanitems record insertion
            } catch (PDOException $e) {  
                throw $e;
            }
        }

        public function insertLoanItem(LoanItem $loanItem) : void {
            try {
                $sql = "INSERT INTO LoanItems (LoanID, BookID)
                                    VALUES(:cloanID, :cbookID)";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cloanID', $loanItem->getLoanID());
                $stmt->bindValue(':cbookID', $loanItem->getBookID());

                $stmt->execute();
            } catch (PDOException $e) {  
                throw $e;
            }
        }

        public function hasOverDueBooks(int $memberID) : int {
            try {
                $sql = "SELECT COUNT(*) 
                        FROM LoanItems li
                        JOIN Loans l ON li.LoanID = l.LoanID
                        WHERE l.MemberID = :cmemberID
                        AND li.ReturnDate IS NULL
                        AND l.DueDate < CURDATE()";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cmemberID', $memberID);

                $stmt->execute();
                return (int) $stmt->fetchColumn(); // retrieves the integer value from the first column in the result set i.e. count digit
            } catch (PDOException $e) {  
                throw $e;
            }
        }

        public function getCurrentLoanCount(int $memberID) : int {
            try {
                $sql = "SELECT COUNT(*) 
                        FROM LoanItems li
                        JOIN Loans l ON li.LoanID = l.LoanID
                        WHERE l.MemberID = :cmemberID
                        AND li.ReturnDate IS NULL";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cmemberID', $memberID);

                $stmt->execute();
                return (int) $stmt->fetchColumn(); // retrieves the integer value from the first column in the result set i.e. count digit
            } catch (PDOException $e) {  
                throw $e;
            }
        }

        public function processLoan(Loan $loan, array $booksInCart) : void {
            // https://www.php.net/manual/en/pdo.begintransaction.php
            $this->pdo->beginTransaction();

            try {
                $loanID = $this->insertLoan($loan);

                foreach($booksInCart as $bookInCart) {
                    $loanItem = new LoanItem($loanID, $bookInCart->getId());
                    $this->insertLoanItem($loanItem);
                }

                $this->pdo->commit();
            } catch(Exception $e) {
                $this->pdo->rollBack();
                throw $e;
            }
        }
    }
?>