<?php 
    /** 
     * Handles database operations for the loans table in the library system.
     * 
     * Provides methods to retrieve and add loans and loan items from the database.
     * 
     * @author Dan
     * @version 1.0
    */
    class LoanRepository {
        /**
         * The database connection.
         * 
         * @var pdo
         */
        private PDO $pdo;

        /**
         * Creates a new LoanRepository instance.
         * 
         * @param PDO $pdo The database connection
         */
        public function __construct(PDO $pdo) {
            $this->pdo = $pdo;
        }

        /**
         * Retrieves all loans from the database.
         * 
         * @return array An array of Loan objects, or an empty array if none found.
         */
        public function getAllLoans() : array {
            $sql = "SELECT * From Loans";
            $stmt = $this->pdo->prepare($sql);
            $stmt->execute();

            $rows = $stmt->fetchAll();
            $loans = [];

            foreach($rows as $row) {
                $loans[] = new Loan(
                    DateTime::createFromFormat("Y-m-d",$row["LoanDate"]),
                    DateTime::createFromFormat("Y-m-d", $row["DueDate"]),
                    $row["MemberID"],
                    $row["LoanID"]
                );
            }

            return $loans;
        }

        /**
         * Adds a new loan transaction to the database.
         * 
         * @param Loan $loan The Loan object to be added.
         * @return int The loan ID automatically generated by MariaDB which will be used when inserting
         * loan items.
         */
        public function insertLoan(Loan $loan) : int {
            try {
                $sql = "INSERT INTO Loans (LoanDate, DueDate, MemberID)
                                    VALUES(:cloanDate, :cdueDate, :cmemberID)";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cloanDate', $loan->getLoanDate()->format('Y-m-d'));
                $stmt->bindValue(':cdueDate', $loan->getDueDate()->format('Y-m-d'));
                $stmt->bindValue(':cmemberID', $loan->getMemberID());

                $stmt->execute();
                //https://stackoverflow.com/questions/10680943/pdo-get-the-last-id-inserted
                return (int) $this->pdo->lastInsertId(); // get the loan ID generated by maria db for loanitems record insertion
            } catch (PDOException $e) {  
                throw new Exception("Error in inserting loan. Please try again.");
            }
        }

        /**
         * Updates the LoanDate and DueDate of a loan.
         * 
         * @return void
         * 
         * @see LoanRepository::updateLoanDetails()
         */
        public function updateLoanDetails(Loan $loan) : void {
            $sql = "UPDATE Loans SET LoanDate = :cLoanDate, DueDate = :cDueDate WHERE LoanID = :cLoanID";

            $stmt = $this->pdo->prepare($sql);
            $stmt->bindValue(":cLoanDate", $loan->getLoanDate()->format("Y-m-d"));
            $stmt->bindValue(":cDueDate", $loan->getDueDate()->format("Y-m-d"));
            $stmt->bindValue(":cLoanID", $loan->getLoanID());

            $stmt->execute();
        }

        /**
         * Retrieves all loan items from the database.
         * 
         * @return array An array of LoanItem objects, or an empty array if none found.
         */
        public function getAllLoanItems() : array {
            $sql = "SELECT * From LoanItems";
            $stmt = $this->pdo->prepare($sql);
            $stmt->execute();

            $rows = $stmt->fetchAll();
            $loanItems = [];

            foreach($rows as $row) {
                $loanItems[] = new LoanItem(
                    $row["LoanID"],
                    $row["BookID"],
                    $row["ReturnDate"] ? DateTime::createFromFormat("Y-m-d", $row["ReturnDate"]) : null
                );
            }

            return $loanItems;
        }

        /**
         * Adds a new loan item transaction to the database.
         * 
         * @param LoanItem $loanItem The LoanItem object to be added.
         */
        public function insertLoanItem(LoanItem $loanItem) : void {
            try {
                $sql = "INSERT INTO LoanItems (LoanID, BookID)
                                    VALUES(:cloanID, :cbookID)";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cloanID', $loanItem->getLoanID());
                $stmt->bindValue(':cbookID', $loanItem->getBookID());

                $stmt->execute();
            } catch (PDOException $e) {  
                throw new Exception("Error in inserting loan item. Please try again");
            }
        }

        /**
         * Retrieves the count of books currently on loan to a member that are overdue.
         * 
         * @param int $member The member id.
         * @return int The count of books.
         */
        public function hasOverDueBooks(int $memberID) : int {
            try {
                $sql = "SELECT COUNT(*) 
                        FROM LoanItems li
                        JOIN Loans l ON li.LoanID = l.LoanID
                        WHERE l.MemberID = :cmemberID
                        AND li.ReturnDate IS NULL
                        AND l.DueDate < CURDATE()";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cmemberID', $memberID);

                $stmt->execute();
                return (int) $stmt->fetchColumn(); // retrieves the integer value from the first column in the result set i.e. count digit
            } catch (PDOException $e) {  
                throw new Exception("Could not retrieve overdue book count.");
            }
        }

        /**
         * Retrieves the count of books currently on loan to a member.
         * This includes due and overdue books.
         * 
         * @param int $member The member id.
         * @return int The count of books.
         */
        public function getCurrentLoanCount(int $memberID) : int {
            try {
                $sql = "SELECT COUNT(*) 
                        FROM LoanItems li
                        JOIN Loans l ON li.LoanID = l.LoanID
                        WHERE l.MemberID = :cmemberID
                        AND li.ReturnDate IS NULL";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cmemberID', $memberID);

                $stmt->execute();
                return (int) $stmt->fetchColumn(); // retrieves the integer value from the first column in the result set i.e. count digit
            } catch (PDOException $e) {  
                throw new Exception("Could not retrieve current loan count.");
            }
        }

        /**
         * Executes the main transaction process.
         * 
         * Processes the loan by insering a loan record and inserts a loan item record for
         * each book in the cart.
         * 
         * @param LoanItem $loanItem The LoanItem object to be added.
         */
        public function processLoan(Loan $loan, array $booksInCart) : void {
            // https://www.php.net/manual/en/pdo.begintransaction.php
            $this->pdo->beginTransaction();

            try {
                $loanID = $this->insertLoan($loan);

                foreach($booksInCart as $bookInCart) {
                    $loanItem = new LoanItem($loanID, $bookInCart->getId());
                    $this->insertLoanItem($loanItem);
                }

                $this->pdo->commit();
            } catch(Exception $e) {
                $this->pdo->rollBack();
                throw new Exception("Error in processing loan transaction.");
            }
        }

        /**
         * Retrieves the books currently on loan to a member.
         * 
         * @param int $member The member id.
         * @return array An array of Book objects.
         */
        public function getLoanedBooks(int $memberID) : array {
             try {
                $sql = "SELECT b.*
                        FROM LoanItems li
                        JOIN Loans l ON li.LoanID = l.LoanID
                        JOIN Books b ON li.BookID = b.BookID
                        WHERE l.MemberID = :cmemberID
                        AND li.ReturnDate IS NULL";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cmemberID', $memberID);

                $stmt->execute();
                $rows = $stmt->fetchAll();

                $loans = [];

                foreach($rows as $row) {
                    $loans[] = new Book (
                        $row['Title'],
                        $row['Author'],
                        $row['Description'],
                        $row['ISBN'],
                        $row['Genre'],
                        $row['Publisher'],
                        $row['PublicationDate'],
                        $row['Status'],
                        $row['BookID']
                    );
                }

                return $loans;
            } catch (PDOException $e) {  
                throw new Exception("Error in retrieving loaned books.");
            }
        }

        /**
         * Executes the secondary transaction process.
         * 
         * Updates the return date of each book to the current date.
         * 
         * @param array $selectedToReturn An array of book ID's the user has selected to be 
         * returned.
         * 
         * @return void
         */
        public function processReturn(array $selectedToReturn) : void {
            // https://www.php.net/manual/en/pdo.begintransaction.php
            $this->pdo->beginTransaction();

            try {
                foreach($selectedToReturn as $bookID) {
                    $this->updateLoanReturnDate($bookID);
                }
                
                $this->pdo->commit();
            } catch(Exception $e) {
                $this->pdo->rollBack();
                throw new Exception("Error in processing return.");
            }
        }

        /**
         * Updates the return date of each book to the current date.
         * 
         * @param int $bookID The loanitem that contains the book ID to be updated.
         * 
         * @return void
         */
        public function updateLoanReturnDate(int $bookID) : void {
            try {
                $sql = "UPDATE LoanItems 
                        SET ReturnDate = CURDATE() 
                        WHERE BookID = :cbookID";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cbookID', $bookID);

                $stmt->execute();
            } catch(Exception $e) {
                $this->pdo->rollBack();
                throw new Exception("Error in updating loan return date.");
            }
        }

        /**
         * Retrieves the loan ID of the active loan using the book ID.
         * 
         * @param int $bookID The loanitem that contains the book ID.
         * 
         * @return int The loan ID of the loan the book is associated with.
         */
        public function getLoanByBookID(int $bookID) : int {
            try {
                $sql = "SELECT l.LoanID FROM loans l
                        JOIN LoanItems li ON l.LoanID = li.LoanID
                        WHERE li.BookID = :cbookID
                        AND li.ReturnDate IS NULL";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cbookID', $bookID);
                $stmt->execute();  
                
                $row = $stmt->fetch();
                return (int) $row['LoanID'];
            }  catch(Exception $e) {
                throw new Exception("Error in getting loan by book ID.");
            }
        }

        /**
         * Retrieves the count of loans on the system.
         * 
         * @return int The total count of loans.
         */
        public function getTotalLoans() : int {
            try {
                $sql = "SELECT COUNT(DISTINCT LoanID) FROM LoanItems 
                        WHERE ReturnDate IS NULL";

                $stmt = $this->pdo->prepare($sql);
                $stmt->execute();
                return $stmt->fetchColumn();
            } catch(Exception $e) {
                throw new Exception("Error in fetching total loan count.");
            }
        }

        /**
         * Retrieves the five most recent loans from the system.
         * 
         * @return array An array of the five most recent loans containing 
         * member, book and loan information.
         */
        public function getRecentLoans() : array {
            try {
                $sql = "SELECT b.*, m.*, l.LoanDate, l.DueDate, li.ReturnDate
                        FROM Loans l
                        JOIN LoanItems li ON l.LoanID = li.LoanID
                        JOIN Books b ON li.BookID = b.BookID
                        JOIN Members m ON l.MemberID = m.MemberID
                        ORDER BY l.LoanDate DESC
                        LIMIT 5";

                $stmt = $this->pdo->prepare($sql);
                $stmt->execute();

                $rows = $stmt->fetchAll();
                $loans = [];

                foreach($rows as $row) {
                    $loans[] = array(
                        "book" => new Book($row["Title"], $row["Author"], $row["Description"], $row["ISBN"], $row["Genre"],
                                        $row["Publisher"], $row["PublicationDate"], $row["Status"]),
                        "member" => new Member($row["FirstName"], $row["LastName"], $row["DOB"], $row["Phone"], 
                                            $row["Email"],$row["AddressLine1"], $row["AddressLine2"], $row["City"], 
                                            $row["County"], $row["Eircode"], $row["RegistrationDate"], $row["Status"]),
                        "loanDate" => DateTime::createFromFormat('Y-m-d', $row["LoanDate"])->format("l d M Y"),
                        "dueDate" => DateTime::createFromFormat('Y-m-d', $row["DueDate"])->format("l d M Y"),
                        "returnDate" => $row["ReturnDate"]
                    );
                }

                return $loans;
            } catch (Exception $e) {
                throw new Exception("Error in fetching recent loans.");
            }
        }

        /**
         * Retrieves the top three members with the highest loan count.
         * 
         * @return array An array of the three members along with loan count.
         */
        public function getTopBorrowers() : array {
            try {
                $sql = "SELECT m.*, COUNT(*) as LoanCount FROM Loans l
                    JOIN Members m ON l.MemberID = m.MemberID
                    GROUP BY m.MemberID
                    ORDER BY LoanCount DESC
                    LIMIT 3";

                $stmt = $this->pdo->prepare($sql);
                $stmt->execute();

                $rows = $stmt->fetchAll();
                $loans = [];

                foreach($rows as $row) {
                    $loans[] = [
                        "member" => new Member (
                        $row["FirstName"], 
                        $row["LastName"], 
                        $row["DOB"], 
                        $row["Phone"], 
                        $row["Email"],
                        $row["AddressLine1"], 
                        $row["AddressLine2"], 
                        $row["City"], 
                        $row["County"], 
                        $row["Eircode"], 
                        $row["RegistrationDate"], 
                        $row["Status"]
                        ),
                        "loanCount" => $row["LoanCount"]
                    ];
                } 

                return $loans;
            } catch (Exception $e) {
                throw new Exception("Error in fetching top borrowers.");
            }
        }
    }
?>