<?php 
    /** 
     * Handles database operations for the loans table in the library system.
     * 
     * Provides methods to retrieve and add loans and loan items from the database.
     * 
     * @author Dan
     * @version 1.0
    */
    class LoanRepository {
        /**
         * The database connection.
         * 
         * @var pdo
         */
        private PDO $pdo;

        /**
         * Creates a new LoanRepository instance.
         * 
         * @param PDO $pdo The database connection
         */
        public function __construct(PDO $pdo) {
            $this->pdo = $pdo;
        }

        /**
         * Adds a new loan transaction to the database.
         * 
         * @param Loan $loan The Loan object to be added.
         * @return int The loan ID automatically generated by MariaDB which will be used when inserting
         * loan items.
         */
        public function insertLoan(Loan $loan) : int {
            try {
                $sql = "INSERT INTO Loans (LoanDate, DueDate, MemberID)
                                    VALUES(:cloanDate, :cdueDate, :cmemberID)";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cloanDate', $loan->getLoanDate()->format('Y-m-d'));
                $stmt->bindValue(':cdueDate', $loan->getDueDate()->format('Y-m-d'));
                $stmt->bindValue(':cmemberID', $loan->getMemberID());

                $stmt->execute();
                //https://stackoverflow.com/questions/10680943/pdo-get-the-last-id-inserted
                return (int) $this->pdo->lastInsertId(); // get the loan ID generated by maria db for loanitems record insertion
            } catch (PDOException $e) {  
                throw $e;
            }
        }

        /**
         * Adds a new loan item transaction to the database.
         * 
         * @param LoanItem $loanItem The LoanItem object to be added.
         */
        public function insertLoanItem(LoanItem $loanItem) : void {
            try {
                $sql = "INSERT INTO LoanItems (LoanID, BookID)
                                    VALUES(:cloanID, :cbookID)";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cloanID', $loanItem->getLoanID());
                $stmt->bindValue(':cbookID', $loanItem->getBookID());

                $stmt->execute();
            } catch (PDOException $e) {  
                throw $e;
            }
        }

        /**
         * Retrieves the count of books currently on loan to a member that are overdue.
         * 
         * @param int $member The member id.
         * @return int The count of books.
         */
        public function hasOverDueBooks(int $memberID) : int {
            try {
                $sql = "SELECT COUNT(*) 
                        FROM LoanItems li
                        JOIN Loans l ON li.LoanID = l.LoanID
                        WHERE l.MemberID = :cmemberID
                        AND li.ReturnDate IS NULL
                        AND l.DueDate < CURDATE()";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cmemberID', $memberID);

                $stmt->execute();
                return (int) $stmt->fetchColumn(); // retrieves the integer value from the first column in the result set i.e. count digit
            } catch (PDOException $e) {  
                throw $e;
            }
        }

        /**
         * Retrieves the count of books currently on loan to a member.
         * 
         * @param int $member The member id.
         * @return int The count of books.
         */
        public function getCurrentLoanCount(int $memberID) : int {
            try {
                $sql = "SELECT COUNT(*) 
                        FROM LoanItems li
                        JOIN Loans l ON li.LoanID = l.LoanID
                        WHERE l.MemberID = :cmemberID
                        AND li.ReturnDate IS NULL";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cmemberID', $memberID);

                $stmt->execute();
                return (int) $stmt->fetchColumn(); // retrieves the integer value from the first column in the result set i.e. count digit
            } catch (PDOException $e) {  
                throw $e;
            }
        }

        /**
         * Executes the main transaction process.
         * 
         * Processes the loan by insering a loan record and inserts a loan item record for
         * each book in the cart.
         * 
         * @param LoanItem $loanItem The LoanItem object to be added.
         */
        public function processLoan(Loan $loan, array $booksInCart) : void {
            // https://www.php.net/manual/en/pdo.begintransaction.php
            $this->pdo->beginTransaction();

            try {
                $loanID = $this->insertLoan($loan);

                foreach($booksInCart as $bookInCart) {
                    $loanItem = new LoanItem($loanID, $bookInCart->getId());
                    $this->insertLoanItem($loanItem);
                }

                $this->pdo->commit();
            } catch(Exception $e) {
                $this->pdo->rollBack();
                throw $e;
            }
        }

        public function getLoanedBooks(int $memberID) : array {
             try {
                $sql = "SELECT b.*
                        FROM LoanItems li
                        JOIN Loans l ON li.LoanID = l.LoanID
                        JOIN Books b ON li.BookID = b.BookID
                        WHERE l.MemberID = :cmemberID
                        AND li.ReturnDate IS NULL";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cmemberID', $memberID);

                $stmt->execute();
                $rows = $stmt->fetchAll();

                $loans = [];

                foreach($rows as $row) {
                    $loans[] = new Book (
                        $row['Title'],
                        $row['Author'],
                        $row['Description'],
                        $row['ISBN'],
                        $row['Genre'],
                        $row['Publisher'],
                        $row['PublicationDate'],
                        $row['Status'],
                        $row['BookID']
                    );
                }

                return $loans;
            } catch (PDOException $e) {  
                throw $e;
            }
        }

        public function processReturn($loanID, $bookID) : void {
            // https://www.php.net/manual/en/pdo.begintransaction.php
            $this->pdo->beginTransaction();

            try {
                $this->updateLoanReturnDate($loanID, $bookID);
                
                $this->pdo->commit();
                } catch(Exception $e) {
                $this->pdo->rollBack();
                throw $e;
            }
        }

        public function updateLoanReturnDate($loanID, $bookID) : void {
            try {
                $sql = "UPDATE LoanItems 
                        SET ReturnDate = CURDATE() 
                        WHERE LoanID = :cloanID
                        AND BookID = :cbookID";

                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':cloanID', $loanID);
                $stmt->bindValue(':cbookID', $bookID);

                $stmt->execute();
                $this->pdo->commit();
                } catch(Exception $e) {
                $this->pdo->rollBack();
                throw $e;
            }
        }
    }
?>